# Generated by Django 5.1.4 on 2025-01-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostainvestimento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
