# Generated by Django 5.1.4 on 2025-01-19 19:12

import empresarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0003_metricas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='logo',
            field=models.FileField(upload_to='logo', validators=[empresarios.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='pitch',
            field=models.FileField(upload_to='pitchs', validators=[empresarios.models.validate_file_size]),
        ),
    ]
